### ISSUE TITLE
Smusher not working with middleman 4.0.0.alpha6

### ISSUE THREAD

**Issue by KamilLelonek** [middleman/middleman-smusher#8]
```
/Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/extensions.rb:96:in `load': Tried to activate old-style extension: smusher. They are no longer supported. (RuntimeError)
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/extension_manager.rb:37:in `activate'
  from /Users/user_name/Desktop/middleman-coffee-react/config.rb:33:in `block in evaluate_configuration'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/config_context.rb:84:in `instance_exec'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/config_context.rb:84:in `block in execute_configure_callbacks'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/config_context.rb:83:in `each'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/config_context.rb:83:in `execute_configure_callbacks'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/application.rb:293:in `evaluate_configuration'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/application.rb:239:in `initialize'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-cli-4.0.0.alpha.6/lib/middleman-cli/build.rb:51:in `new'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-cli-4.0.0.alpha.6/lib/middleman-cli/build.rb:51:in `build'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-cli-4.0.0.alpha.6/bin/middleman:23:in `<top (required)>'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/bin/middleman:23:in `load'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/bin/middleman:23:in `<main>'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by emilioforrer** [comment]
Try to put the `activate :deploy` inside the `configure :build` block, like this:

```
configure :build do
  activate :deploy do |deploy|
    deploy.method = :rsync
    deploy.host   = 'www.example.com'
    deploy.path   = '/var/www/www.example.com'
    deploy.build_before = true
    # Optional Settings
    # deploy.user  = 'foobar'
    # deploy.port  = 5309 # ssh port, default: 22
    # deploy.clean = true # remove orphaned files on remote host, default: false
    # deploy.flags = '-rltgoDvzO --no-p --del' # add custom flags, default: -avz
  end
end

```

**Comment by bhollis** [comment]
A PR to convert it would be welcome. Otherwise it'll have to wait until 4.0 is actually released.
